ports:
 # 1     4
 # 2     5
 # 3     6
 - id: 1
   pd: /sys/class/power_supply/ucsi-source-psy-USBC000:004
   usb2: /sys/bus/usb/devices/7-1
   usb3: /sys/bus/usb/devices/8-1
   # usb4: TODO
   display: /sys/class/drm/card*-DP-4
   led_matrix:
    id: left
    pos: 0

 - id: 2
   pd: /sys/class/power_supply/ucsi-source-psy-USBC000:003
   usb2: /sys/bus/usb/devices/1-1
   usb3: /sys/bus/usb/devices/2-1
   display: /sys/class/drm/card*-DP-5
   led_matrix:
    id: left
    pos: 1

 - id: 3
   usb2: /sys/bus/usb/devices/1-2.3
   usb3: /sys/bus/usb/devices/2-2.3
   led_matrix:
    id: left
    pos: 2

 - id: 4
   pd: /sys/class/power_supply/ucsi-source-psy-USBC000:001
   usb2: /sys/bus/usb/devices/5-1
   usb3: /sys/bus/usb/devices/6-1
   # usb4: TODO
   display: /sys/class/drm/card*-DP-3
   led_matrix:
    id: right
    pos: 0

 - id: 5
   pd: /sys/class/power_supply/ucsi-source-psy-USBC000:002
   usb2: /sys/bus/usb/devices/1-2.1
   usb3: /sys/bus/usb/devices/2-2.1
   led_matrix:
    id: right
    pos: 1

 - id: 6
   usb2: /sys/bus/usb/devices/1-2.2
   usb3: /sys/bus/usb/devices/2-2.2
   led_matrix:
    id: right
    pos: 2

led_matrices:
- id: right
  serial: /dev/serial/by-path/pci-0000:c4:00.3-usb-0:3.3:1.0

- id: left
  serial: /dev/serial/by-path/pci-0000:c4:00.3-usb-0:4.2:1.0
