ports:
 # TODO: Try udev + ID_PATH or ID_PATH_WITH_USB_REVISION and fix it to the PCIe addresses, which are constant for sure

 # 1     4
 # 2     5
 # 3     6
 - id: 1
   pd: /sys/class/power_supply/ucsi-source-psy-USBC000:004
   usb:
    - /sys/bus/usb/devices/7-1 # 2
    - /sys/bus/usb/devices/8-1 # 3
   # usb4: TODO
   display: /sys/class/drm/card*-DP-4
   led_matrix:
    id: left
    pos: 0

 - id: 2
   pd: /sys/class/power_supply/ucsi-source-psy-USBC000:003
   usb:
    - /sys/bus/usb/devices/1-1 # 2
    - /sys/bus/usb/devices/2-1 # 3
   display: /sys/class/drm/card*-DP-5
   led_matrix:
    id: left
    pos: 1

 - id: 3
   usb:
    - /sys/bus/usb/devices/1-2.3 # 2
    - /sys/bus/usb/devices/2-2.3 # 3
   led_matrix:
    id: left
    pos: 2

 - id: 4
   pd: /sys/class/power_supply/ucsi-source-psy-USBC000:001
   usb:
    - /sys/bus/usb/devices/5-1 # 2
    - /sys/bus/usb/devices/6-1 # 3
   # usb4: TODO
   display: /sys/class/drm/card*-DP-3
   led_matrix:
    id: right
    pos: 0

 - id: 5
   pd: /sys/class/power_supply/ucsi-source-psy-USBC000:002
   usb:
    - /sys/bus/usb/devices/1-2.1 # 2
    - /sys/bus/usb/devices/2-2.1 # 3
   led_matrix:
    id: right
    pos: 1

 - id: 6
   usb:
    - /sys/bus/usb/devices/1-2.2 # 2
    - /sys/bus/usb/devices/2-2.2 # 3
   led_matrix:
    id: right
    pos: 2

led_matrices:
- id: right
  serial: /dev/serial/by-path/pci-0000:c4:00.3-usb-0:3.3:1.0

- id: left
  serial: /dev/serial/by-path/pci-0000:c4:00.3-usb-0:4.2:1.0

render:
  frame_time_seconds: 0.5

sleep:
  idle_seconds: 20
  individual_ports: true
